### ISSUE TITLE
AttributeError: '_SingleProcessDataLoaderIter' object has no attribute 'next'

### ISSUE THREAD

**Issue by dengchengxifrank** [yonghanzhang94/img2pointcloud#1]
thank you for your work!when i try this command "python trainG.py" I get 
Traceback (most recent call last):
  File "trainG.py", line 98, in <module>
    data = data_iter.next()
AttributeError: '_SingleProcessDataLoaderIter' object has no attribute 'next'

and i wonder if you can help me to solve this problem?

**Comment by dengchengxifrank** [comment]
solve by changing data_iter.next() to data_iter.__next__()

**Comment by 2catycm** [comment]
> solve by changing data_iter.next() to data_iter.**next**()

what was the difference, you just bold it

**Comment by dengchengxifrank** [comment]
change it to data_iter.__next__()

**Comment by dengchengxifrank** [comment]
add the underscore before and after next.
